### ISSUE TITLE
Parameter "range" is missing

### ISSUE THREAD

**Issue by robdplatt** [SteveWinward/GoogleSheetsWrapper#1]
I have many tabs in a sheet I'd like to pull data from. Each sheet might have a slightly different schema. Instead of having to reformat all of the sheets or create many strongly typed Repositories & Records, I thought maybe I could use the sheetHelper.GetRows() method to just iterate through the rows and pull the data I want based on a variety of column names, maybe?

Anyway, simply trying to return a range throws an error.

Sample code:

```
Dim range = New GoogleSheetsWrapper.SheetRange(sheetName, 1, 1)
Dim rows = sheetHelper.GetRows(range)
```

```
Google.GoogleApiException
  HResult=0x80131500
  Message=Parameter "range" is missing
  Source=Google.Apis
  StackTrace:
   at Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   at Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at GoogleSheetsWrapper.BaseSheetHelper.GetRows(SheetRange range)
   at GoogleSheetsExtract.Program.VB$StateMachine_1_EnumerateSheetDefault.MoveNext() in C:\Users\rplatt\source\repos\GoogleSheetsExtract\GoogleSheetsExtract\Program.vb:line 60
   at GoogleSheetsExtract.Program.Main(String[] args) in C:\Users\rplatt\source\repos\GoogleSheetsExtract\GoogleSheetsExtract\Program.vb:line 25

```

Not sure if I'm doing something wrong. 

Any help is appreciated.
Thanks!

**Comment by SteveWinward** [comment]
Thanks for posting and glad to see someone else is trying to use the code I wrote!

Try adding one more parameter to the SheetRange constructor for the index of the last column you want to include in the row. Without that I don’t think my code today can make a request to get a row. Example below is to get rows that have the first 8 columns of cell data for each row. 

Dim range = New GoogleSheetsWrapper.SheetRange(sheetName, 1, 1,8)

Dim rows = sheetHelper.GetRows(range)

Let me know if this helps!  If not I can do a more detailed example for you.

**Comment by SteveWinward** [comment]
FYI. I released version 1.0.18 which will no longer throw that error message. Instead it will return all rows that include only the first column. If you want to include additional columns you need to specify the max column index to be included into the result set. 

Hope this helps.

**Comment by robdplatt** [comment]
@SteveWinward,

That did it! Thank you. I had/have a fairly time consuming project at hand. I had been eyeing this repo for awhile and thought it was the perfect time to start using it. I hope it picks up more followers!

**Comment by SteveWinward** [comment]
Excellent. Good luck with your project. 

Let me know if you have any other feedback on the library.
